In [72]:
import numpy as np
import pandas as pd
from unidecode import unidecode

In [73]:
df = pd.read_excel('datosEncuesta.xlsx', sheet_name='Respuestas de formulario 1')


df

,Marca temporal,¿Cuál es tu género?,¿Cuál es tu edad?,¿Cuál es tu altura? (metros),¿Cuál es tu peso actual? (libras),¿Realizas alguna de estas actividades físicas?,¿Cuántos días a la semana entrenas?,¿Cuántas horas entrenas al día?,¿Cuánto tiempo llevas entrenando constantemente? (Sin pausas),¿Cuál es tu enfoque de rutina de ejercicio actual?,...,¿Cuántos vasos de agua bebes al día?,¿Con qué frecuencia consumes fruta?,¿Con qué frecuencia consumes verdura?,¿Cuál es tu motivo principal para hacer ejercicio?,¿Cuántas horas al día le puedes dedicar al ejercicio?,¿Tienes experiencia en entrenamiento de fuerza?,¿Tienes experiencia en entrenamiento cardiovascular?,¿Tienes acceso a un gimnasio o centro de fitness?\n,¿Tienes algun área específica de tu cuerpo en la que quieras trabajar?,¿Con qué intensidad te gustarían tus entrenamientos?
0,2023-03-23 17:17:07.693,Femenino,22,1.59,145.0,Ejercicio en casa,3-4,Media hora o menos,menos de 1 año,Resistencia,...,1-3,4.0,4.0,"Pérdida de Peso, Salud",Menos de una hora,Sí,Sí,Sí,Cuerpo en general,Intensos
1,2023-03-23 17:17:37.303,Masculino,22,1.84,205.0,Gimnasio,3-4,1 hora - 2 horas,3-4 años,Fortalecimiento,...,11-14,2.0,3.0,Definición muscular,1-2,Sí,Sí,No,Pecho,Intensos
2,2023-03-23 19:39:04.412,Masculino,20,1.70,122.0,Gimnasio,3-4,1 hora o menos,menos de 1 año,Fortalecimiento,...,4-7,2.0,2.0,"Aumento de masa muscular, Definición muscular",1-2,Sí,Sí,Sí,Abdomen,Poco Intensos
3,2023-03-23 19:39:21.246,Femenino,25,1.63,120.0,No realizo actividad física pero me encantaría...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"Pérdida de Peso, Aumento de masa muscular, Def...",1-2,Sí,No,Sí,Piernas,Intensos
4,2023-03-23 19:39:26.353,Masculino,18,1.71,110.0,Gimnasio,1-2,1 hora o menos,menos de 1 año,Fortalecimiento,...,4-7,3.0,4.0,Aumento de masa muscular,1-2,No,No,Sí,Espalda,Intensos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,2023-03-25 01:24:10.157,Masculino,22,1.92,187.0,Gimnasio,5-6,Más de 3 horas,más de 7 años,Fortalecimiento,...,11-14,2.0,2.0,"Aumento de masa muscular, Definición muscular,...",Más de 4 horas,Sí,Sí,Sí,Cuerpo en general,Muy Intensos
217,2023-03-25 05:28:44.458,Masculino,48,1.80,182.0,No realizo actividad física pero me encantaría...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Salud,Menos de una hora,No,Sí,Sí,Cuerpo en general,Intensos
218,2023-03-25 07:12:46.469,Femenino,22,1.56,130.0,Ejercicio en casa,5-6,1 hora o menos,3-4 años,Resistencia,...,4-7,3.0,3.0,"Aumento de masa muscular, Definición muscular",1-2,Sí,No,Sí,Cuerpo en general,Intensos
219,2023-03-25 10:30:34.223,Masculino,56,1.70,157.0,Ejercicio en casa,3-4,1 hora o menos,menos de 1 año,Fortalecimiento,...,1-3,5.0,3.0,Aumento de masa muscular,Menos de una hora,No,No,No,Cuerpo en general,Intensos
220,2023-03-26 06:53:50.432,Masculino,50,1.78,180.0,Gimnasio,3-4,1 hora o menos,más de 7 años,Flexibilidad,...,8-10,3.0,3.0,Pérdida de Peso,1-2,No,Sí,Sí,Abdomen,Intensos

In [74]:

categorias, indice = pd.factorize(df['¿Cuál es tu género?'])

df['genero'] = categorias

categorias_genero = df[['genero', '¿Cuál es tu género?']]

df.drop('¿Cuál es tu género?', axis=1, inplace=True)


categorias_genero = categorias_genero.drop_duplicates(subset=['genero'])

categorias_genero

    genero  ¿Cuál es tu género?
0        0             Femenino
1        1            Masculino
90       2  Prefiero no decirlo

In [75]:
categorias, indice = pd.factorize(df['¿Realizas alguna de estas actividades físicas? '])

df['actividad_fisica'] = categorias

categorias_actividades = df[['actividad_fisica', '¿Realizas alguna de estas actividades físicas? ']]

df.drop('¿Realizas alguna de estas actividades físicas? ', axis=1, inplace=True)


categorias_actividades = categorias_actividades.drop_duplicates(subset=['actividad_fisica'])

categorias_actividades

   actividad_fisica    ¿Realizas alguna de estas actividades físicas?
0                 0                                  Ejercicio en casa
1                 1                                           Gimnasio
3                 2  No realizo actividad física pero me encantaría...

In [76]:
categorias, indice = pd.factorize(df['¿Cuántos días a la semana entrenas? '])

df['dias_entreno'] = categorias

categorias_dias = df[['dias_entreno', '¿Cuántos días a la semana entrenas? ']]

df.drop('¿Cuántos días a la semana entrenas? ', axis=1, inplace=True)


categorias_dias = categorias_dias.drop_duplicates(subset=['dias_entreno'])

categorias_dias

    dias_entreno ¿Cuántos días a la semana entrenas?
0              0                                  3-4
3             -1                                  NaN
4              1                                  1-2
9              2                       Todos los días
13             3                                  5-6

In [77]:
categorias, indice = pd.factorize(df['¿Cuántas horas entrenas al día?'])

df['horas_entreno'] = categorias

categorias_dias = df[['horas_entreno', '¿Cuántas horas entrenas al día?']]

df.drop('¿Cuántas horas entrenas al día?', axis=1, inplace=True)


categorias_horas = categorias_dias.drop_duplicates(subset=['horas_entreno'])

categorias_horas

    horas_entreno ¿Cuántas horas entrenas al día?
0               0              Media hora o menos
1               1                1 hora - 2 horas
2               2                  1 hora o menos
3              -1                             NaN
9               3                  Más de 3 horas
15              4               2 horas - 3 horas

In [78]:
categorias, indice = pd.factorize(df['¿Cuánto tiempo llevas entrenando constantemente? (Sin pausas) '])

df['entreno_constante'] = categorias

categorias_entreno_constante = df[['entreno_constante', '¿Cuánto tiempo llevas entrenando constantemente? (Sin pausas) ']]

df.drop('¿Cuánto tiempo llevas entrenando constantemente? (Sin pausas) ', axis=1, inplace=True)


categorias_entreno_constante = categorias_entreno_constante.drop_duplicates(subset=['entreno_constante'])

categorias_entreno_constante

,entreno_constante,¿Cuánto tiempo llevas entrenando constantemente? (Sin pausas)
0,0,menos de 1 año
1,1,3-4 años
3,-1,NaN
5,2,1 - 2 años
9,3,5-6 años
17,4,más de 7 años

In [79]:
categorias, indice = pd.factorize(df['¿Cuál es tu enfoque de rutina de ejercicio actual?'])

df['enfoque'] = categorias

categorias_enfoque = df[['enfoque', '¿Cuál es tu enfoque de rutina de ejercicio actual?']]

df.drop('¿Cuál es tu enfoque de rutina de ejercicio actual?', axis=1, inplace=True)


categorias_enfoque = categorias_enfoque.drop_duplicates(subset=['enfoque'])

categorias_enfoque

    enfoque ¿Cuál es tu enfoque de rutina de ejercicio actual?
0         0                                        Resistencia
1         1                                    Fortalecimiento
3        -1                                                NaN
77        2                                       Flexibilidad

In [80]:
df['¿Qué tipos de ejercicios o áreas trabajas en tu rutina actual?'] = df['¿Qué tipos de ejercicios o áreas trabajas en tu rutina actual?'].str.replace(' ', '')
df['¿Qué tipos de ejercicios o áreas trabajas en tu rutina actual?'] = df['¿Qué tipos de ejercicios o áreas trabajas en tu rutina actual?'].str.split(',')


dummies = pd.get_dummies(df['¿Qué tipos de ejercicios o áreas trabajas en tu rutina actual?'].apply(pd.Series).stack(), prefix='areas_').sum(level=0)


# reemplazar NaN con 0
dummies = dummies.fillna(0)

# Booleanos a Int
dummies = dummies.astype(int)

df = pd.concat([df, dummies], axis=1)


df.drop('¿Qué tipos de ejercicios o áreas trabajas en tu rutina actual?', axis=1, inplace=True)

df

C:\Users\adali\AppData\Local\Temp\ipykernel_14112\1139994463.py:5: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  dummies = pd.get_dummies(df['¿Qué tipos de ejercicios o áreas trabajas en tu rutina actual?'].apply(pd.Series).stack(), prefix='areas_').sum(level=0)

,Marca temporal,¿Cuál es tu edad?,¿Cuál es tu altura? (metros),¿Cuál es tu peso actual? (libras),\n¿Consideras que tu rutina actual es efectiva?,¿Cómo consideras que esta tu físico en estos momentos?,¿Cómo consideras que esta tu salud en estos momentos?,¿Consume alguno de estos productos?,¿Cuántas horas sueles dormir por noche?,¿Cómo calificarías tus hábitos alimenticios actuales?\n,...,dias_entreno,horas_entreno,entreno_constante,enfoque,areas__Abdomen,areas__Brazo,areas__Cardio,areas__Espalda,areas__Pecho,areas__Pierna
0,2023-03-23 17:17:07.693,22,1.59,145.0,Tal vez,7.0,9.0,Otro,5-6,3.0,...,0,0,0,0,1.0,0.0,1.0,0.0,0.0,0.0
1,2023-03-23 17:17:37.303,22,1.84,205.0,Sí,7.0,9.0,Proteína,7-8,3.0,...,0,1,1,1,1.0,1.0,1.0,1.0,1.0,1.0
2,2023-03-23 19:39:04.412,20,1.70,122.0,Tal vez,1.0,7.0,Proteína,3-4,4.0,...,0,2,0,1,1.0,1.0,1.0,0.0,0.0,1.0
3,2023-03-23 19:39:21.246,25,1.63,120.0,NaN,NaN,NaN,NaN,NaN,NaN,...,-1,-1,-1,-1,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-03-23 19:39:26.353,18,1.71,110.0,Tal vez,4.0,6.0,Nada,3-4,3.0,...,1,2,0,1,1.0,1.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,2023-03-25 01:24:10.157,22,1.92,187.0,Sí,7.0,9.0,"Proteína, Creatina, Pre-Entreno",7-8,3.0,...,3,3,4,1,1.0,1.0,1.0,1.0,1.0,1.0
217,2023-03-25 05:28:44.458,48,1.80,182.0,NaN,NaN,NaN,NaN,NaN,NaN,...,-1,-1,-1,-1,NaN,NaN,NaN,NaN,NaN,NaN
218,2023-03-25 07:12:46.469,22,1.56,130.0,Tal vez,7.0,8.0,"Proteína, Creatina",5-6,4.0,...,3,2,1,0,0.0,1.0,0.0,1.0,0.0,1.0
219,2023-03-25 10:30:34.223,56,1.70,157.0,Tal vez,5.0,6.0,Nada,5-6,3.0,...,0,2,0,1,1.0,1.0,1.0,1.0,1.0,1.0
220,2023-03-26 06:53:50.432,50,1.78,180.0,Tal vez,7.0,7.0,Nada,5-6,4.0,...,0,2,4,2,0.0,0.0,1.0,0.0,0.0,0.0

In [81]:
categorias, indice = pd.factorize(df['\n¿Consideras que tu rutina actual es efectiva?'])

df['efectividad'] = categorias

categorias_efectividad = df[['efectividad', '\n¿Consideras que tu rutina actual es efectiva?']]

df.drop('\n¿Consideras que tu rutina actual es efectiva?', axis=1, inplace=True)


categorias_efectividad = categorias_efectividad.drop_duplicates(subset=['efectividad'])

categorias_efectividad

    efectividad \n¿Consideras que tu rutina actual es efectiva?
0             0                                         Tal vez
1             1                                              Sí
3            -1                                             NaN
18            2                                              No

In [82]:
df['¿Consume alguno de estos productos?'] = df['¿Consume alguno de estos productos?'].str.replace(' ', '')
df['¿Consume alguno de estos productos?'] = df['¿Consume alguno de estos productos?'].str.split(',')


dummies = pd.get_dummies(df['¿Consume alguno de estos productos?'].apply(pd.Series).stack(), prefix='consumo_').sum(level=0)


# reemplazar NaN con 0
dummies = dummies.fillna(0)

# Booleanos a Int
dummies = dummies.astype(int)

df = pd.concat([df, dummies], axis=1)


df.drop('¿Consume alguno de estos productos?', axis=1, inplace=True)

df

C:\Users\adali\AppData\Local\Temp\ipykernel_14112\2671010937.py:5: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  dummies = pd.get_dummies(df['¿Consume alguno de estos productos?'].apply(pd.Series).stack(), prefix='consumo_').sum(level=0)

,Marca temporal,¿Cuál es tu edad?,¿Cuál es tu altura? (metros),¿Cuál es tu peso actual? (libras),¿Cómo consideras que esta tu físico en estos momentos?,¿Cómo consideras que esta tu salud en estos momentos?,¿Cuántas horas sueles dormir por noche?,¿Cómo calificarías tus hábitos alimenticios actuales?\n,¿Cuál es su principal fuente de comida diaria?,¿Cuál es su segunda fuente de comida diaria?,...,areas__Cardio,areas__Espalda,areas__Pecho,areas__Pierna,efectividad,consumo__Creatina,consumo__Nada,consumo__Otro,consumo__Pre-Entreno,consumo__Proteína
0,2023-03-23 17:17:07.693,22,1.59,145.0,7.0,9.0,5-6,3.0,Carbohidratos,Proteina,...,1.0,0.0,0.0,0.0,0,0.0,0.0,1.0,0.0,0.0
1,2023-03-23 17:17:37.303,22,1.84,205.0,7.0,9.0,7-8,3.0,Proteína,Carbohidratos,...,1.0,1.0,1.0,1.0,1,0.0,0.0,0.0,0.0,1.0
2,2023-03-23 19:39:04.412,20,1.70,122.0,1.0,7.0,3-4,4.0,Carbohidratos,Grasas,...,1.0,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,1.0
3,2023-03-23 19:39:21.246,25,1.63,120.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN
4,2023-03-23 19:39:26.353,18,1.71,110.0,4.0,6.0,3-4,3.0,Carbohidratos,Proteina,...,0.0,1.0,1.0,1.0,0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,2023-03-25 01:24:10.157,22,1.92,187.0,7.0,9.0,7-8,3.0,Carbohidratos,Proteina,...,1.0,1.0,1.0,1.0,1,1.0,0.0,0.0,1.0,1.0
217,2023-03-25 05:28:44.458,48,1.80,182.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN
218,2023-03-25 07:12:46.469,22,1.56,130.0,7.0,8.0,5-6,4.0,Proteína,Carbohidratos,...,0.0,1.0,0.0,1.0,0,1.0,0.0,0.0,0.0,1.0
219,2023-03-25 10:30:34.223,56,1.70,157.0,5.0,6.0,5-6,3.0,Carbohidratos,Grasas,...,1.0,1.0,1.0,1.0,0,0.0,1.0,0.0,0.0,0.0
220,2023-03-26 06:53:50.432,50,1.78,180.0,7.0,7.0,5-6,4.0,Carbohidratos,Proteina,...,1.0,0.0,0.0,0.0,0,0.0,1.0,0.0,0.0,0.0

In [83]:
categorias, indice = pd.factorize(df['¿Cuántas horas sueles dormir por noche?'])

df['horas_dormir'] = categorias

categorias_dormir = df[['horas_dormir', '¿Cuántas horas sueles dormir por noche?']]

df.drop('¿Cuántas horas sueles dormir por noche?', axis=1, inplace=True)


categorias_dormir = categorias_dormir.drop_duplicates(subset=['horas_dormir'])

categorias_dormir

    horas_dormir ¿Cuántas horas sueles dormir por noche?
0              0                                     5-6
1              1                                     7-8
2              2                                     3-4
3             -1                                     NaN
22             3                                    9-10

In [84]:
categorias, indice = pd.factorize(df['¿Cuál es su principal fuente de comida diaria?'])

df['fuente_energia1'] = categorias

categorias_fuente1 = df[['fuente_energia1', '¿Cuál es su principal fuente de comida diaria?']]

df.drop('¿Cuál es su principal fuente de comida diaria?', axis=1, inplace=True)


categorias_fuente1 = categorias_fuente1.drop_duplicates(subset=['fuente_energia1'])

categorias_fuente1

    fuente_energia1 ¿Cuál es su principal fuente de comida diaria?
0                 0                                  Carbohidratos
1                 1                                       Proteína
3                -1                                            NaN
64                2                                         Grasas

In [85]:
categorias, indice = pd.factorize(df['¿Cuál es su segunda fuente de comida diaria?'])

df['fuente_energia2'] = categorias

categorias_fuente2 = df[['fuente_energia2', '¿Cuál es su segunda fuente de comida diaria?']]

df.drop('¿Cuál es su segunda fuente de comida diaria?', axis=1, inplace=True)


categorias_fuente2 = categorias_fuente2.drop_duplicates(subset=['fuente_energia2'])

categorias_fuente2

   fuente_energia2 ¿Cuál es su segunda fuente de comida diaria?
0                0                                     Proteina
1                1                                Carbohidratos
2                2                                       Grasas
3               -1                                          NaN

In [86]:
categorias, indice = pd.factorize(df['¿Cuántos vasos de agua bebes al día?'])

df['agua'] = categorias

categorias_agua = df[['agua', '¿Cuántos vasos de agua bebes al día?']]

df.drop('¿Cuántos vasos de agua bebes al día?', axis=1, inplace=True)


categorias_agua = categorias_agua.drop_duplicates(subset=['agua'])

categorias_agua

    agua ¿Cuántos vasos de agua bebes al día?
0      0                                  1-3
1      1                                11-14
2      2                                  4-7
3     -1                                  NaN
5      3                                 8-10
60     4                            Más de 15

In [87]:
df['¿Cuál es tu motivo principal para hacer ejercicio? '] = df['¿Cuál es tu motivo principal para hacer ejercicio? '].str.replace(' ', '')
df['¿Cuál es tu motivo principal para hacer ejercicio? '] = df['¿Cuál es tu motivo principal para hacer ejercicio? '].str.split(',')


dummies = pd.get_dummies(df['¿Cuál es tu motivo principal para hacer ejercicio? '].apply(pd.Series).stack(), prefix='motivo_').sum(level=0)


# reemplazar NaN con 0
dummies = dummies.fillna(0)

# Booleanos a Int
dummies = dummies.astype(int)

df = pd.concat([df, dummies], axis=1)


df.drop('¿Cuál es tu motivo principal para hacer ejercicio? ', axis=1, inplace=True)

df

C:\Users\adali\AppData\Local\Temp\ipykernel_14112\3092596193.py:5: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  dummies = pd.get_dummies(df['¿Cuál es tu motivo principal para hacer ejercicio? '].apply(pd.Series).stack(), prefix='motivo_').sum(level=0)

,Marca temporal,¿Cuál es tu edad?,¿Cuál es tu altura? (metros),¿Cuál es tu peso actual? (libras),¿Cómo consideras que esta tu físico en estos momentos?,¿Cómo consideras que esta tu salud en estos momentos?,¿Cómo calificarías tus hábitos alimenticios actuales?\n,¿Con qué frecuencia consumes fruta?,¿Con qué frecuencia consumes verdura?,¿Cuántas horas al día le puedes dedicar al ejercicio?,...,consumo__Pre-Entreno,consumo__Proteína,horas_dormir,fuente_energia1,fuente_energia2,agua,motivo__Aumentodemasamuscular,motivo__Definiciónmuscular,motivo__PérdidadePeso,motivo__Salud
0,2023-03-23 17:17:07.693,22,1.59,145.0,7.0,9.0,3.0,4.0,4.0,Menos de una hora,...,0.0,0.0,0,0,0,0,0,0,1,1
1,2023-03-23 17:17:37.303,22,1.84,205.0,7.0,9.0,3.0,2.0,3.0,1-2,...,0.0,1.0,1,1,1,1,0,1,0,0
2,2023-03-23 19:39:04.412,20,1.70,122.0,1.0,7.0,4.0,2.0,2.0,1-2,...,0.0,1.0,2,0,2,2,1,1,0,0
3,2023-03-23 19:39:21.246,25,1.63,120.0,NaN,NaN,NaN,NaN,NaN,1-2,...,NaN,NaN,-1,-1,-1,-1,1,1,1,0
4,2023-03-23 19:39:26.353,18,1.71,110.0,4.0,6.0,3.0,3.0,4.0,1-2,...,0.0,0.0,2,0,0,2,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,2023-03-25 01:24:10.157,22,1.92,187.0,7.0,9.0,3.0,2.0,2.0,Más de 4 horas,...,1.0,1.0,1,0,0,1,1,1,0,1
217,2023-03-25 05:28:44.458,48,1.80,182.0,NaN,NaN,NaN,NaN,NaN,Menos de una hora,...,NaN,NaN,-1,-1,-1,-1,0,0,0,1
218,2023-03-25 07:12:46.469,22,1.56,130.0,7.0,8.0,4.0,3.0,3.0,1-2,...,0.0,1.0,0,1,1,2,1,1,0,0
219,2023-03-25 10:30:34.223,56,1.70,157.0,5.0,6.0,3.0,5.0,3.0,Menos de una hora,...,0.0,0.0,0,0,2,0,1,0,0,0
220,2023-03-26 06:53:50.432,50,1.78,180.0,7.0,7.0,4.0,3.0,3.0,1-2,...,0.0,0.0,0,0,0,3,0,0,1,0

In [88]:
categorias, indice = pd.factorize(df['¿Cuántas horas al día le puedes dedicar al ejercicio?'])

df['disponibilidad_tiempo'] = categorias

categorias_disponibilidad_tiempo = df[['disponibilidad_tiempo', '¿Cuántas horas al día le puedes dedicar al ejercicio?']]

df.drop('¿Cuántas horas al día le puedes dedicar al ejercicio?', axis=1, inplace=True)


categorias_disponibilidad_tiempo = categorias_disponibilidad_tiempo.drop_duplicates(subset=['disponibilidad_tiempo'])

categorias_disponibilidad_tiempo

,disponibilidad_tiempo,¿Cuántas horas al día le puedes dedicar al ejercicio?
0,0,Menos de una hora
1,1,1-2
9,2,Más de 4 horas
15,3,3-4

In [89]:
categorias, indice = pd.factorize(df['¿Tienes experiencia en entrenamiento de fuerza?'])

df['experiencia_fuerza'] = categorias

categorias_fuerza= df[['experiencia_fuerza', '¿Tienes experiencia en entrenamiento de fuerza?']]

df.drop('¿Tienes experiencia en entrenamiento de fuerza?', axis=1, inplace=True)


categorias_fuerza = categorias_fuerza.drop_duplicates(subset=['experiencia_fuerza'])

categorias_fuerza

   experiencia_fuerza ¿Tienes experiencia en entrenamiento de fuerza?
0                   0                                              Sí
4                   1                                              No

In [90]:
categorias, indice = pd.factorize(df['¿Tienes experiencia en entrenamiento cardiovascular?'])

df['experiencia_cardio'] = categorias

categorias_cardio= df[['experiencia_cardio', '¿Tienes experiencia en entrenamiento cardiovascular?']]

df.drop('¿Tienes experiencia en entrenamiento cardiovascular?', axis=1, inplace=True)


categorias_cardio = categorias_cardio.drop_duplicates(subset=['experiencia_cardio'])

categorias_cardio

   experiencia_cardio ¿Tienes experiencia en entrenamiento cardiovascular?
0                   0                                                 Sí
3                   1                                                 No

In [91]:
categorias, indice = pd.factorize(df['¿Tienes acceso a un gimnasio o centro de fitness?\n'])

df['acceso'] = categorias

categorias_acceso= df[['acceso', '¿Tienes acceso a un gimnasio o centro de fitness?\n']]

df.drop('¿Tienes acceso a un gimnasio o centro de fitness?\n', axis=1, inplace=True)


categorias_acceso = categorias_acceso.drop_duplicates(subset=['acceso'])

categorias_acceso

   acceso ¿Tienes acceso a un gimnasio o centro de fitness?\n
0       0                                                 Sí
1       1                                                 No

In [92]:
categorias, indice = pd.factorize(df['¿Tienes algun área específica de tu cuerpo en la que quieras trabajar?'])

df['preferencia_area'] = categorias

categorias_preferencia_area= df[['preferencia_area', '¿Tienes algun área específica de tu cuerpo en la que quieras trabajar?']]

df.drop('¿Tienes algun área específica de tu cuerpo en la que quieras trabajar?', axis=1, inplace=True)


categorias_preferencia_area = categorias_preferencia_area.drop_duplicates(subset=['preferencia_area'])

categorias_preferencia_area

,preferencia_area,¿Tienes algun área específica de tu cuerpo en la que quieras trabajar?
0,0,Cuerpo en general
1,1,Pecho
2,2,Abdomen
3,3,Piernas
4,4,Espalda
26,5,Brazos

In [93]:
categorias, indice = pd.factorize(df['¿Con qué intensidad te gustarían tus entrenamientos?'])

df['intensidad'] = categorias

categorias_intensidad= df[['intensidad', '¿Con qué intensidad te gustarían tus entrenamientos?']]

df.drop('¿Con qué intensidad te gustarían tus entrenamientos?', axis=1, inplace=True)


categorias_intensidad = categorias_intensidad.drop_duplicates(subset=['intensidad'])

categorias_intensidad

   intensidad ¿Con qué intensidad te gustarían tus entrenamientos?
0           0                                           Intensos
2           1                                      Poco Intensos
9           2                                       Muy Intensos

In [94]:
df.rename(columns={'¿Cuál es tu edad?': 'Edad', '¿Cuál es tu altura? (metros)': 'Altura', "¿Cuál es tu peso actual? (libras)": "Peso", "¿Cómo consideras que esta tu físico en estos momentos? ":"estado_fisico", "¿Cómo consideras que esta tu salud en estos momentos?":"salud", "¿Cómo calificarías tus hábitos alimenticios actuales?\n": "alimentacion", "¿Con qué frecuencia consumes fruta?": "fruta_consumo", "¿Con qué frecuencia consumes verdura?":"verdura_consumo", "consumo__Proteína":"consumo_proteina", "motivo__PérdidadePeso":"motivo__Perdida_Peso", "motivo__Definiciónmuscular":"motivo__Definicion_muscular"}, inplace=True)

df

,Marca temporal,Edad,Altura,Peso,estado_fisico,salud,alimentacion,fruta_consumo,verdura_consumo,genero,...,motivo__Aumentodemasamuscular,motivo__Definicion_muscular,motivo__Perdida_Peso,motivo__Salud,disponibilidad_tiempo,experiencia_fuerza,experiencia_cardio,acceso,preferencia_area,intensidad
0,2023-03-23 17:17:07.693,22,1.59,145.0,7.0,9.0,3.0,4.0,4.0,0,...,0,0,1,1,0,0,0,0,0,0
1,2023-03-23 17:17:37.303,22,1.84,205.0,7.0,9.0,3.0,2.0,3.0,1,...,0,1,0,0,1,0,0,1,1,0
2,2023-03-23 19:39:04.412,20,1.70,122.0,1.0,7.0,4.0,2.0,2.0,1,...,1,1,0,0,1,0,0,0,2,1
3,2023-03-23 19:39:21.246,25,1.63,120.0,NaN,NaN,NaN,NaN,NaN,0,...,1,1,1,0,1,0,1,0,3,0
4,2023-03-23 19:39:26.353,18,1.71,110.0,4.0,6.0,3.0,3.0,4.0,1,...,1,0,0,0,1,1,1,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,2023-03-25 01:24:10.157,22,1.92,187.0,7.0,9.0,3.0,2.0,2.0,1,...,1,1,0,1,2,0,0,0,0,2
217,2023-03-25 05:28:44.458,48,1.80,182.0,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,1,0,1,0,0,0,0
218,2023-03-25 07:12:46.469,22,1.56,130.0,7.0,8.0,4.0,3.0,3.0,0,...,1,1,0,0,1,0,1,0,0,0
219,2023-03-25 10:30:34.223,56,1.70,157.0,5.0,6.0,3.0,5.0,3.0,1,...,1,0,0,0,0,1,1,1,0,0
220,2023-03-26 06:53:50.432,50,1.78,180.0,7.0,7.0,4.0,3.0,3.0,1,...,0,0,1,0,1,1,0,0,2,0

In [95]:
df.drop('Marca temporal', axis=1, inplace=True)

df

,Edad,Altura,Peso,estado_fisico,salud,alimentacion,fruta_consumo,verdura_consumo,genero,actividad_fisica,...,motivo__Aumentodemasamuscular,motivo__Definicion_muscular,motivo__Perdida_Peso,motivo__Salud,disponibilidad_tiempo,experiencia_fuerza,experiencia_cardio,acceso,preferencia_area,intensidad
0,22,1.59,145.0,7.0,9.0,3.0,4.0,4.0,0,0,...,0,0,1,1,0,0,0,0,0,0
1,22,1.84,205.0,7.0,9.0,3.0,2.0,3.0,1,1,...,0,1,0,0,1,0,0,1,1,0
2,20,1.70,122.0,1.0,7.0,4.0,2.0,2.0,1,1,...,1,1,0,0,1,0,0,0,2,1
3,25,1.63,120.0,NaN,NaN,NaN,NaN,NaN,0,2,...,1,1,1,0,1,0,1,0,3,0
4,18,1.71,110.0,4.0,6.0,3.0,3.0,4.0,1,1,...,1,0,0,0,1,1,1,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,22,1.92,187.0,7.0,9.0,3.0,2.0,2.0,1,1,...,1,1,0,1,2,0,0,0,0,2
217,48,1.80,182.0,NaN,NaN,NaN,NaN,NaN,1,2,...,0,0,0,1,0,1,0,0,0,0
218,22,1.56,130.0,7.0,8.0,4.0,3.0,3.0,0,0,...,1,1,0,0,1,0,1,0,0,0
219,56,1.70,157.0,5.0,6.0,3.0,5.0,3.0,1,0,...,1,0,0,0,0,1,1,1,0,0
220,50,1.78,180.0,7.0,7.0,4.0,3.0,3.0,1,1,...,0,0,1,0,1,1,0,0,2,0

In [96]:
df = df.fillna(-1)

In [97]:
#CREACIÓN FUNCIONES

#Función IMC
def imc(estatura, peso):
    kilos = peso/2.2
    indice = round(kilos / (estatura ** 2), 2)
    return indice

#Función Grasa corporal
def grasa_corporal(imc, edad, genero):
    gc= (1.20*imc)+(0.23*edad)-(10.8*genero)-5.4
    return round(gc,2)

#Funcion Grasa Magra
def grasa_corporal_magra(peso,  imc):
    kilos = peso/2.2
    
    mcmkg= kilos - (imc*kilos)/100
    return round(mcmkg,2)

In [98]:
df = df.assign(IMC=df.apply(lambda row: imc(row['Altura'], row['Peso']), axis=1))

df

,Edad,Altura,Peso,estado_fisico,salud,alimentacion,fruta_consumo,verdura_consumo,genero,actividad_fisica,...,motivo__Definicion_muscular,motivo__Perdida_Peso,motivo__Salud,disponibilidad_tiempo,experiencia_fuerza,experiencia_cardio,acceso,preferencia_area,intensidad,IMC
0,22,1.59,145.0,7.0,9.0,3.0,4.0,4.0,0,0,...,0,1,1,0,0,0,0,0,0,26.07
1,22,1.84,205.0,7.0,9.0,3.0,2.0,3.0,1,1,...,1,0,0,1,0,0,1,1,0,27.52
2,20,1.70,122.0,1.0,7.0,4.0,2.0,2.0,1,1,...,1,0,0,1,0,0,0,2,1,19.19
3,25,1.63,120.0,-1.0,-1.0,-1.0,-1.0,-1.0,0,2,...,1,1,0,1,0,1,0,3,0,20.53
4,18,1.71,110.0,4.0,6.0,3.0,3.0,4.0,1,1,...,0,0,0,1,1,1,0,4,0,17.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,22,1.92,187.0,7.0,9.0,3.0,2.0,2.0,1,1,...,1,0,1,2,0,0,0,0,2,23.06
217,48,1.80,182.0,-1.0,-1.0,-1.0,-1.0,-1.0,1,2,...,0,0,1,0,1,0,0,0,0,25.53
218,22,1.56,130.0,7.0,8.0,4.0,3.0,3.0,0,0,...,1,0,0,1,0,1,0,0,0,24.28
219,56,1.70,157.0,5.0,6.0,3.0,5.0,3.0,1,0,...,0,0,0,0,1,1,1,0,0,24.69
220,50,1.78,180.0,7.0,7.0,4.0,3.0,3.0,1,1,...,0,1,0,1,1,0,0,2,0,25.82

In [99]:
df = df.assign(grasa_corporal=df.apply(lambda row: grasa_corporal(row['IMC'], row['Edad'], row['genero']), axis=1))

df

,Edad,Altura,Peso,estado_fisico,salud,alimentacion,fruta_consumo,verdura_consumo,genero,actividad_fisica,...,motivo__Perdida_Peso,motivo__Salud,disponibilidad_tiempo,experiencia_fuerza,experiencia_cardio,acceso,preferencia_area,intensidad,IMC,grasa_corporal
0,22,1.59,145.0,7.0,9.0,3.0,4.0,4.0,0,0,...,1,1,0,0,0,0,0,0,26.07,30.94
1,22,1.84,205.0,7.0,9.0,3.0,2.0,3.0,1,1,...,0,0,1,0,0,1,1,0,27.52,21.88
2,20,1.70,122.0,1.0,7.0,4.0,2.0,2.0,1,1,...,0,0,1,0,0,0,2,1,19.19,11.43
3,25,1.63,120.0,-1.0,-1.0,-1.0,-1.0,-1.0,0,2,...,1,0,1,0,1,0,3,0,20.53,24.99
4,18,1.71,110.0,4.0,6.0,3.0,3.0,4.0,1,1,...,0,0,1,1,1,0,4,0,17.10,8.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,22,1.92,187.0,7.0,9.0,3.0,2.0,2.0,1,1,...,0,1,2,0,0,0,0,2,23.06,16.53
217,48,1.80,182.0,-1.0,-1.0,-1.0,-1.0,-1.0,1,2,...,0,1,0,1,0,0,0,0,25.53,25.48
218,22,1.56,130.0,7.0,8.0,4.0,3.0,3.0,0,0,...,0,0,1,0,1,0,0,0,24.28,28.80
219,56,1.70,157.0,5.0,6.0,3.0,5.0,3.0,1,0,...,0,0,0,1,1,1,0,0,24.69,26.31
220,50,1.78,180.0,7.0,7.0,4.0,3.0,3.0,1,1,...,1,0,1,1,0,0,2,0,25.82,26.28

In [100]:
df = df.assign(grasa_corporal_magra=df.apply(lambda row: grasa_corporal_magra(row['Peso'], row['IMC']), axis=1))

df

,Edad,Altura,Peso,estado_fisico,salud,alimentacion,fruta_consumo,verdura_consumo,genero,actividad_fisica,...,motivo__Salud,disponibilidad_tiempo,experiencia_fuerza,experiencia_cardio,acceso,preferencia_area,intensidad,IMC,grasa_corporal,grasa_corporal_magra
0,22,1.59,145.0,7.0,9.0,3.0,4.0,4.0,0,0,...,1,0,0,0,0,0,0,26.07,30.94,48.73
1,22,1.84,205.0,7.0,9.0,3.0,2.0,3.0,1,1,...,0,1,0,0,1,1,0,27.52,21.88,67.54
2,20,1.70,122.0,1.0,7.0,4.0,2.0,2.0,1,1,...,0,1,0,0,0,2,1,19.19,11.43,44.81
3,25,1.63,120.0,-1.0,-1.0,-1.0,-1.0,-1.0,0,2,...,0,1,0,1,0,3,0,20.53,24.99,43.35
4,18,1.71,110.0,4.0,6.0,3.0,3.0,4.0,1,1,...,0,1,1,1,0,4,0,17.10,8.46,41.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,22,1.92,187.0,7.0,9.0,3.0,2.0,2.0,1,1,...,1,2,0,0,0,0,2,23.06,16.53,65.40
217,48,1.80,182.0,-1.0,-1.0,-1.0,-1.0,-1.0,1,2,...,1,0,1,0,0,0,0,25.53,25.48,61.61
218,22,1.56,130.0,7.0,8.0,4.0,3.0,3.0,0,0,...,0,1,0,1,0,0,0,24.28,28.80,44.74
219,56,1.70,157.0,5.0,6.0,3.0,5.0,3.0,1,0,...,0,0,1,1,1,0,0,24.69,26.31,53.74
220,50,1.78,180.0,7.0,7.0,4.0,3.0,3.0,1,1,...,0,1,1,0,0,2,0,25.82,26.28,60.69

In [101]:
df.to_csv('dataLimpia.csv', index=False)